name: Welcome Newcomers

on:
  push:
    branches:
      - main
  issues:
    types: [opened]
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Greet newcomers
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACCESSTOKEN }}
          script: |
            const eventName = context.eventName;

            let message = '';

            if (eventName === 'push') {
              message = `🎉 Thank you for your contribution to the \`main\` branch! We appreciate your effort.`;
              const commits = context.payload.commits;
              for (const commit of commits) {
                await github.rest.repos.createCommitComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  commit_sha: commit.id,
                  body: message
                });
              }
            } else if (eventName === 'issues') {
              message = `👋 Thanks for opening this issue! We're glad you're here. The team will look into it shortly.`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });
            } else if (eventName === 'pull_request') {
              message = `🚀 Thanks for submitting this pull request to \`main\`! The team will review it soon.`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });
            }
