# .github/workflows/welcome.yml
name: Welcome Newcomers

on:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Post a welcome message
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACCESSTOKEN }}
          script: |
            const event = context.eventName;

            if (event === 'push') {
              const commits = context.payload.commits || [];
              for (const commit of commits) {
                await github.rest.repos.createCommitComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  commit_sha: commit.id,
                  body: '🎉 Thank you for your contribution to the `main` branch!'
                });
              }
            }

            if (event === 'issues') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: '👋 Thanks for opening this issue! We\'re happy to have you here.'
              });
            }

            if (event === 'pull_request') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '🚀 Thanks for submitting this pull request! We\'ll review it shortly.'
              });
            }
