name: Welcome Contributor

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  welcome-on-issues-prs:
    if: github.event_name == 'issues' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            👋 Hello @${{ github.actor }}!  
            Thanks for opening your first issue. We appreciate your contribution and will get back to you soon.
          pr-message: >
            🎉 Hi @${{ github.actor }}!  
            Thank you for your first pull request! The team will review it shortly.

  welcome-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Get committer username
        id: extract
        run: |
          echo "username=${{ github.actor }}" >> $GITHUB_OUTPUT

      - name: Check if first commit by user
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = '${{ steps.extract.outputs.username }}';
            const commits = await github.paginate(
              github.rest.repos.listCommits,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                author: username
              }
            );

            const isFirst = commits.length <= 1;
            core.setOutput("isFirst", isFirst);
            core.setOutput("username", username);

      - name: Create welcome issue
        if: steps.check.outputs.isFirst == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🎉 Welcome @${{ steps.check.outputs.username }} to the repository!`,
              body: `Hi @${{ steps.check.outputs.username }}! 🎉\n\nThank you for making your first commit to the \`main\` branch. We appreciate your contribution and look forward to more from you. 🚀`,
            });
