name: Welcome Newcomers

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      # Ensure the ACCESS_TOKEN is set properly
      - name: Check ACCESS_TOKEN
        run: |
          echo "ACCESS_TOKEN is set to: ${{ secrets.ACCESSTOKEN }}"
        
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.ACCESSTOKEN }}
          issue-message: |
            👋 Hello and welcome! Thank you for opening your first issue in this repo.
            We're glad to have you here. Feel free to ask any questions or give feedback!
          pr-message: |
            🎉 Thanks for your first pull request! We're excited to review it.
            Stay awesome and keep contributing!
